### ISSUE TITLE
Errors running vgg16 oktopk

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [Shigangli/Ok-Topk#6]
Hi, thanks for the repo!! I am running the Ok-topk algorithm on the VGG network:
the setup/command i run is the same `vgg16_oktopk.sh`,  it shows the errors below after some iterations, any ideas on how to fix it?
```
Exception in thread allreducer:
Traceback (most recent call last):
  File "xxxxx/miniconda3/envs/xxxx/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "xxxxx/miniconda3/envs/xxxx/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eecs/xxxxx/Ok-Topk/VGG/allreducer.py", line 643, in run
    self._boundaries[new_name][i] = global_boundaries[i]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
Thanks!

**Comment by LiuXiaoxuanPKU** [comment]
solved, turns out to be the problem of launching mpi
